# Generated by Django 4.0.4 on 2022-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
