# Generated by Django 4.0.4 on 2022-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FilePathField(path='/Users/macbook/Desktop/Momentum/homework/django-music-Scooper1920/albums/static/img/'),
        ),
    ]
